-- SELECT CONCAT('INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (',
--     CAST(id AS CHAR), ', 0, ',
--     CAST(category AS CHAR), ', ',
--     QUOTE(name), ', ',
--     QUOTE(description), ', ',
--     QUOTE(model), ', ',
--     QUOTE(ccts), ', 0, 0, 0.0, ',
--     CAST(showname AS CHAR), ', 0, 0, '''', 0, ',
--     CAST(visitors_max AS CHAR), ', 0, ''0|0|'', 0, ',
--     CAST(is_hidden AS CHAR), ', ''2023-05-03 00:00:00'', ''2023-05-03 00:00:00'', 1, 0, 0, 0);')
--     FROM rooms WHERE owner_id = 0;

-- SELECT CONCAT('INSERT INTO groups_details (name, description, owner_id, room_id, badge, recommended, background, views, topics, group_type, forum_type, forum_premission, alias, created_at) VALUES (',
--     QUOTE(name), ', ',
--     QUOTE(description), ', 1, 0, ',
--     QUOTE(badge), ', 0, ',
--     QUOTE(background), ', 0, 0, 0, 0, 0, ',
--     QUOTE(alias), ', ''2023-05-03 00:00:00'');')
--     FROM groups_details WHERE alias IN ('help', 'officialhabboguides', 'battleball_rebound', 'snow_storm', 'wobble_squabble', 'lido');

-- SELECT
--     CONCAT('INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, ',
--     CAST(x AS CHAR), ', ',
--     CAST(y AS CHAR), ', ',
--     CAST(z AS CHAR), ', ',
--     CAST(sticker_id AS CHAR), ', ',
--     CAST(skin_id AS CHAR), ', ',
--     CAST(CASE
--     WHEN group_id = 1 THEN 2
--     WHEN group_id = 3 THEN 1
--     WHEN group_id = 71 THEN 3
--     WHEN group_id = 65 THEN 4
--     WHEN group_id = 66 THEN 5
--     WHEN group_id = 67 THEN 6
--     END AS CHAR), ', ',
--     QUOTE(text), ', 1, '''');') AS Statement
--     FROM cms_stickers WHERE group_id IN (65, 1, 66, 3, 71, 67) AND is_placed = 1;

TRUNCATE TABLE cms_alerts;
TRUNCATE TABLE cms_forum_replies;
TRUNCATE TABLE cms_forums_read_replies;
TRUNCATE TABLE cms_forum_threads;
TRUNCATE TABLE cms_guestbook_entries;
TRUNCATE TABLE cms_minimail;
TRUNCATE TABLE cms_recommended;
TRUNCATE TABLE cms_stickers;

TRUNCATE TABLE games_played_history;

TRUNCATE TABLE groups_details;
TRUNCATE TABLE groups_edit_sessions;
TRUNCATE TABLE groups_memberships;
TRUNCATE TABLE homes_details;
TRUNCATE TABLE homes_edit_sessions;
TRUNCATE TABLE homes_ratings;
TRUNCATE TABLE housekeeping_audit_log;

TRUNCATE TABLE items;
TRUNCATE TABLE items_moodlight_presets;
TRUNCATE TABLE items_pets;
TRUNCATE TABLE items_photos;
TRUNCATE TABLE items_teleporter_links;
TRUNCATE TABLE messenger_categories;
TRUNCATE TABLE messenger_friends;
TRUNCATE TABLE messenger_messages;
TRUNCATE TABLE messenger_requests;

TRUNCATE TABLE rooms;
TRUNCATE TABLE rooms_ads;
TRUNCATE TABLE rooms_bans;
TRUNCATE TABLE rooms_events;
TRUNCATE TABLE rooms_rights;
TRUNCATE TABLE room_visits;
TRUNCATE TABLE room_chatlogs;

TRUNCATE TABLE site_articles;

TRUNCATE TABLE soundmachine_disks;
TRUNCATE TABLE soundmachine_playlists;
TRUNCATE TABLE soundmachine_songs;
TRUNCATE TABLE soundmachine_tracks;
TRUNCATE TABLE users;
TRUNCATE TABLE users_achievements;
TRUNCATE TABLE users_badges;
TRUNCATE TABLE users_club_gifts;
TRUNCATE TABLE users_effects;
TRUNCATE TABLE users_ip_logs;
TRUNCATE TABLE users_mutes;
TRUNCATE TABLE users_referred;
TRUNCATE TABLE users_room_favourites;
TRUNCATE TABLE users_room_votes;
TRUNCATE TABLE users_statistics;
TRUNCATE TABLE users_tags;
TRUNCATE TABLE users_transactions;
TRUNCATE TABLE users_wardrobes;
TRUNCATE TABLE vouchers;
TRUNCATE TABLE vouchers_history;
TRUNCATE TABLE vouchers_items;
TRUNCATE TABLE wordfilter;

TRUNCATE TABLE yearly_gifts_log;

INSERT INTO users (username, password, figure, sex, rank) VALUES ('User', '$argon2id$v=19$m=65536,t=2,p=1$6LXSvmza2pYOvCzQVMHjUw$NQ2T2gQl7n3J9Tb9oQlFdV3iKoY0y5bBr+Bf0UiG1kE', 'ch-210-66.hd-180-1.lg-270-82.hr-100-34.sh-290-80', 'M', 8);

INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (1, 0, 3, 'Welcome Lounge', 'welcome_lounge', 'newbie_lobby', 'hh_room_nlobby', 0, 0, 0.0, 0, 0, 0, '', 0, 40, 0, '0|0|', 0, 0, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (2, 0, 5, 'Theatredome', 'theatredrome', 'theater', 'hh_room_theater', 0, 0, 0.0, 0, 0, 0, '', 0, 100, 0, '0|0|', 0, 0, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (3, 0, 5, 'Library', 'library', 'library', 'hh_room_library', 0, 0, 0.0, 0, 0, 0, '', 0, 30, 0, '0|0|', 0, 0, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (4, 0, 5, 'TV Studio', 'tv_studio', 'tv_studio', 'hh_room_tv_studio_general', 0, 0, 0.0, 0, 0, 0, '', 0, 20, 0, '0|0|', 0, 0, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (5, 0, 5, 'Cinema', 'habbo_cinema', 'cinema_a', 'hh_room_cinema', 0, 0, 0.0, 0, 0, 0, '', 0, 50, 0, '0|0|', 0, 0, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (6, 0, 5, 'Power Gym', 'sport', 'sport', 'hh_room_sport', 0, 0, 0.0, 0, 0, 0, '', 0, 35, 0, '0|0|', 0, 0, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (7, 0, 5, 'Olympic Stadium', 'ballroom', 'ballroom', 'hh_room_ballroom', 0, 0, 0.0, 0, 0, 0, '', 0, 50, 0, '0|0|', 0, 0, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (8, 0, 6, 'Habbo Kitchen', 'hotel_kitchen', 'cr_kitchen', 'hh_room_kitchen', 0, 0, 0.0, 0, 0, 0, '', 0, 20, 0, '0|0|', 0, 0, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (9, 0, 6, 'The Dirty Duck Pub', 'the_dirty_duck_pub', 'pub_a', 'hh_room_pub', 0, 0, 0.0, 0, 0, 0, '', 0, 40, 0, '0|0|', 0, 0, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (10, 0, 6, 'Cafe Ole', 'cafe_ole', 'cafe_ole', 'hh_room_cafe', 0, 0, 0.0, 0, 0, 0, '', 0, 35, 0, '0|0|', 0, 0, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (11, 0, 6, 'Eric\'s Eaterie', 'eric\'s_eaterie', 'cr_cafe', 'hh_room_erics', 0, 0, 0.0, 0, 0, 0, '', 0, 35, 0, '0|0|', 0, 0, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (12, 0, 6, 'Space Cafe', 'space_cafe', 'space_cafe', 'hh_room_space_cafe', 0, 0, 0.0, 0, 0, 0, '', 0, 35, 0, '0|0|', 0, 0, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (13, 0, 7, 'Rooftop Terrace', 'rooftop', 'rooftop', 'hh_room_rooftop', 0, 0, 0.0, 0, 0, 0, '', 0, 30, 0, '0|0|', 0, 0, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (14, 0, 7, 'Rooftop Cafe', 'rooftop', 'rooftop_2', 'hh_room_rooftop', 0, 0, 0.0, 0, 0, 0, '', 0, 20, 0, '0|0|', 0, 1, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (15, 0, 6, 'Palazzo Pizza', 'pizza', 'pizza', 'hh_room_pizza', 0, 0, 0.0, 0, 0, 0, '', 0, 40, 0, '0|0|', 0, 0, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (16, 0, 6, 'Habburgers', 'habburger\'s', 'habburger', 'hh_room_habburger', 0, 0, 0.0, 0, 0, 0, '', 0, 40, 0, '0|0|', 0, 0, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (17, 0, 8, 'Grandfathers Lounge', 'dusty_lounge', 'dusty_lounge', 'hh_room_dustylounge', 0, 0, 0.0, 0, 0, 0, '', 0, 45, 0, '0|0|', 0, 0, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (18, 0, 7, 'Oriental Tearoom', 'tearoom', 'tearoom', 'hh_room_tearoom', 0, 0, 0.0, 0, 0, 0, '', 0, 40, 0, '0|0|', 0, 0, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (19, 0, 7, 'Oldskool Lounge', 'old_skool', 'old_skool0', 'hh_room_old_skool', 0, 0, 0.0, 0, 0, 0, '', 0, 45, 0, '0|0|', 0, 0, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (20, 0, 7, 'Oldskool Dancefloor', 'old_skool', 'old_skool1', 'hh_room_old_skool', 0, 0, 0.0, 0, 0, 0, '', 0, 45, 0, '0|0|', 0, 1, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (21, 0, 7, 'The Chromide Club', 'the_chromide_club', 'malja_bar_a', 'hh_room_disco', 0, 0, 0.0, 0, 0, 0, '', 0, 45, 0, '0|0|', 0, 0, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (22, 0, 7, 'The Chromide Club II', 'the_chromide_club', 'malja_bar_b', 'hh_room_disco', 0, 0, 0.0, 0, 0, 0, '', 0, 50, 0, '0|0|', 0, 1, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (23, 0, 7, 'Club Massiva', 'club_massiva', 'bar_a', 'hh_room_bar', 0, 0, 0.0, 0, 0, 0, '', 0, 45, 0, '0|0|', 0, 0, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (24, 0, 7, 'Club Massiva II', 'club_massiva2', 'bar_b', 'hh_room_bar', 0, 0, 0.0, 0, 0, 0, '', 0, 70, 0, '0|0|', 0, 1, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (25, 0, 6, 'Sunset Cafe', 'sunset_cafe', 'sunset_cafe', 'hh_room_sunsetcafe', 0, 0, 0.0, 0, 0, 0, '', 0, 35, 0, '0|0|', 0, 0, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (26, 0, 7, 'Safety Spa', 'cafe_gold', 'cafe_gold0', 'hh_room_gold', 0, 0, 0.0, 0, 0, 0, '', 0, 50, 0, '0|0|', 0, 0, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (27, 0, 9, 'Zen Garden', 'chill', 'chill', 'hh_room_chill', 0, 0, 0.0, 0, 0, 0, '', 0, 30, 0, '0|0|', 0, 0, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (28, 0, 8, 'Club Mammoth', 'club_mammoth', 'club_mammoth', 'hh_room_clubmammoth', 0, 0, 0.0, 0, 0, 0, '', 0, 45, 0, '0|0|', 0, 0, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (29, 0, 9, 'Floating Garden', 'floatinggarden', 'floatinggarden', 'hh_room_floatinggarden', 0, 0, 0.0, 0, 0, 0, '', 0, 80, 0, '0|0|', 0, 0, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (30, 0, 9, 'Picnic Fields', 'picnic', 'picnic', 'hh_room_picnic', 0, 0, 0.0, 0, 0, 0, '', 0, 55, 0, '0|0|', 0, 0, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (31, 0, 9, 'Sun Terrace', 'sun_terrace', 'sun_terrace', 'hh_room_sun_terrace', 0, 0, 0.0, 0, 0, 0, '', 0, 50, 0, '0|0|', 0, 0, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (32, 0, 9, 'Peaceful Park', 'gate_park', 'gate_park', 'hh_room_gate_park', 0, 0, 0.0, 0, 0, 0, '', 0, 50, 0, '0|0|', 0, 0, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (33, 0, 9, 'Peaceful Park - B', 'gate_park', 'gate_park_2', 'hh_room_gate_park', 0, 0, 0.0, 0, 0, 0, '', 0, 50, 0, '0|0|', 0, 1, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (34, 0, 3, 'The Park', 'park', 'park_a', 'hh_room_park,hh_room_park_general', 0, 0, 0.0, 0, 0, 0, '', 0, 45, 0, '0|0|', 0, 0, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (35, 0, 3, 'The Infobus', 'park', 'park_b', 'hh_room_park,hh_people_pool', 0, 0, 0.0, 0, 0, 0, '', 0, 20, 0, '0|0|', 0, 1, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (36, 0, 3, 'Habbo Lido', 'habbo_lido', 'pool_a', 'hh_room_pool,hh_people_pool', 0, 0, 0.0, 0, 0, 0, '', 0, 60, 0, '0|0|', 0, 0, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (37, 0, 3, 'Lido B', 'habbo_lido_ii', 'pool_b', 'hh_room_pool,hh_people_pool', 0, 0, 0.0, 0, 0, 0, '', 0, 60, 0, '0|0|', 0, 1, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (38, 0, 3, 'Rooftop Rumble', 'rooftop_rumble', 'md_a', 'hh_room_terrace,hh_paalu,hh_people_pool,hh_people_paalu', 0, 0, 0.0, 0, 0, 0, '', 0, 50, 0, '0|0|', 0, 0, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (39, 0, 11, 'Main Lobby', 'main_lobby', 'lobby_a', 'hh_room_lobby', 0, 0, 0.0, 0, 0, 0, '', 0, 100, 0, '0|0|', 0, 0, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (40, 0, 11, 'Basement Lobby', 'basement_lobby', 'floorlobby_a', 'hh_room_floorlobbies', 0, 0, 0.0, 0, 0, 0, '', 0, 50, 0, '0|0|', 0, 0, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (41, 0, 11, 'Median Lobby', 'median_lobby', 'floorlobby_b', 'hh_room_floorlobbies', 0, 0, 0.0, 0, 0, 0, '', 0, 50, 0, '0|0|', 0, 0, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (42, 0, 11, 'Skylight Lobby', 'skylight_lobby', 'floorlobby_c', 'hh_room_floorlobbies', 0, 0, 0.0, 0, 0, 0, '', 0, 50, 0, '0|0|', 0, 0, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (43, 0, 6, 'Ice Cafe', 'ice_cafe', 'ice_cafe', 'hh_room_icecafe', 0, 0, 0.0, 0, 0, 0, '', 0, 25, 0, '0|0|', 0, 0, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (44, 0, 6, 'Net Cafe', 'netcafe', 'netcafe', 'hh_room_netcafe', 0, 0, 0.0, 0, 0, 0, '', 0, 25, 0, '0|0|', 0, 0, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (45, 0, 5, 'Beauty Salon', 'beauty_salon_loreal', 'beauty_salon0', 'hh_room_beauty_salon_general', 0, 0, 0.0, 0, 0, 0, '', 0, 25, 0, '0|0|', 0, 0, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (46, 0, 5, 'The Den', 'the_den', 'cr_staff', 'hh_room_den', 0, 0, 0.0, 0, 0, 0, '', 0, 100, 0, '0|0|', 0, 0, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (47, 0, 12, 'Lower Hallways', 'hallway', 'hallway2', 'hh_room_hallway', 0, 0, 0.0, 1, 0, 0, '', 0, 25, 0, '0|0|', 0, 0, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (48, 0, 12, 'Lower Hallways I', 'hallway', 'hallway0', 'hh_room_hallway', 0, 0, 0.0, 1, 0, 0, '', 0, 25, 0, '0|0|', 0, 1, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (49, 0, 12, 'Lower Hallways II', 'hallway', 'hallway1', 'hh_room_hallway', 0, 0, 0.0, 1, 0, 0, '', 0, 25, 0, '0|0|', 0, 1, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (50, 0, 12, 'Lower Hallways III', 'hallway', 'hallway3', 'hh_room_hallway', 0, 0, 0.0, 1, 0, 0, '', 0, 25, 0, '0|0|', 0, 1, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (51, 0, 12, 'Lower Hallways IV', 'hallway', 'hallway5', 'hh_room_hallway', 0, 0, 0.0, 1, 0, 0, '', 0, 25, 0, '0|0|', 0, 1, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (52, 0, 12, 'Lower Hallways V', 'hallway', 'hallway4', 'hh_room_hallway', 0, 0, 0.0, 1, 0, 0, '', 0, 25, 0, '0|0|', 0, 1, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (53, 0, 12, 'Upper Hallways', 'hallway_ii', 'hallway9', 'hh_room_hallway', 0, 0, 0.0, 1, 0, 0, '', 0, 25, 0, '0|0|', 0, 0, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (54, 0, 12, 'Upper Hallways I', 'hallway_ii', 'hallway8', 'hh_room_hallway', 0, 0, 0.0, 1, 0, 0, '', 0, 25, 0, '0|0|', 0, 1, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (55, 0, 12, 'Upper Hallways II', 'hallway_ii', 'hallway7', 'hh_room_hallway', 0, 0, 0.0, 1, 0, 0, '', 0, 25, 0, '0|0|', 0, 1, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (56, 0, 12, 'Upper Hallways III', 'hallway_ii', 'hallway6', 'hh_room_hallway', 0, 0, 0.0, 1, 0, 0, '', 0, 25, 0, '0|0|', 0, 1, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (57, 0, 12, 'Upper Hallways IV', 'hallway_ii', 'hallway10', 'hh_room_hallway', 0, 0, 0.0, 1, 0, 0, '', 0, 25, 0, '0|0|', 0, 1, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (58, 0, 12, 'Upper Hallways V', 'hallway_ii', 'hallway11', 'hh_room_hallway', 0, 0, 0.0, 1, 0, 0, '', 0, 25, 0, '0|0|', 0, 1, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (59, 0, 7, 'Star Lounge', 'star_lounge', 'star_lounge', 'hh_room_starlounge', 0, 0, 0.0, 1, 0, 0, '', 0, 35, 0, '0|0|', 0, 0, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (60, 0, 8, 'Club Orient', 'orient', 'orient', 'hh_room_orient', 0, 0, 0.0, 1, 0, 0, '', 0, 35, 0, '0|0|', 0, 0, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (61, 0, 13, 'Cunning Fox Gamehall', 'cunning_fox_gamehall', 'entryhall', 'hh_room_gamehall,hh_games', 0, 0, 0.0, 1, 0, 0, '', 0, 25, 0, '0|0|', 0, 0, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (62, 0, 13, 'TicTacToe hall', 'cunning_fox_gamehall/1', 'hallA', 'hh_room_gamehall,hh_games', 0, 0, 0.0, 1, 0, 0, '', 0, 25, 0, '0|0|', 0, 1, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (63, 0, 13, 'Battleships hall', 'cunning_fox_gamehall/2', 'hallB', 'hh_room_gamehall,hh_games', 0, 0, 0.0, 1, 0, 0, '', 0, 25, 0, '0|0|', 0, 1, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (64, 0, 13, 'Chess hall', 'cunning_fox_gamehall/3', 'hallC', 'hh_room_gamehall,hh_games', 0, 0, 0.0, 1, 0, 0, '', 0, 25, 0, '0|0|', 0, 1, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (65, 0, 13, 'Poker hall', 'cunning_fox_gamehall/4', 'hallD', 'hh_room_gamehall,hh_games', 0, 0, 0.0, 1, 0, 0, '', 0, 25, 0, '0|0|', 0, 1, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (66, 0, 13, 'Battleball Lobby', 'bb_lobby_beginner_0', 'bb_lobby_1', 'hh_game_bb,hh_game_bb_room,hh_game_bb_ui,hh_gamesys', 0, 0, 0.0, 1, 0, 0, '', 0, 200, 0, '0|0|', 0, 0, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (67, 0, 13, 'Snowstorm Lobby', 'sw_lobby_beginner_0', 'snowwar_lobby_1', 'hh_gamesys,hh_game_snowwar,hh_game_snowwar_room,hh_game_snowwar_ui', 0, 0, 0.0, 1, 0, 0, '', 0, 200, 0, '0|0|', 0, 0, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (68, 0, 5, 'Imperial Palace', 'emperors', 'emperors', 'hh_room_emperors', 0, 0, 0.0, 0, 0, 0, '', 0, 30, 0, '0|0|', 0, 0, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);
INSERT INTO rooms (id, owner_id, category, name, description, model, ccts, wallpaper, floor, landscape, showname, superusers, accesstype, password, visitors_now, visitors_max, rating, icon_data, group_id, is_hidden, created_at, updated_at, legacy_room, room_cost_coins, room_cost_pixels, legacy_lock) VALUES (69, 0, 5, 'Beauty Salon II', 'beauty_salon_loreal', 'beauty_salon1', 'hh_room_beauty_salon_general', 0, 0, 0.0, 0, 0, 0, '', 0, 25, 0, '0|0|', 0, 1, '2023-05-03 00:00:00', '2023-05-03 00:00:00', 1, 0, 0, 0);

INSERT INTO groups_details (name, description, owner_id, room_id, badge, recommended, background, views, topics, group_type, forum_type, forum_premission, alias, created_at) VALUES ('Welcome to Habbo', 'New here? Check out this page to find out all you need to get started. Find out what Habbo\'s all about, how to get around, where to go to play games, and all the cool and interesting things going on. See you in the Hotel!', 1, 0, 'b2102Xs06114s03134', 0, 'head_guides_germany', 0, 0, 0, 0, 0, 'help', '2023-05-03 00:00:00');
INSERT INTO groups_details (name, description, owner_id, room_id, badge, recommended, background, views, topics, group_type, forum_type, forum_premission, alias, created_at) VALUES ('Habbo Guides (Official)', 'The official Habbo Guides Group.', 1, 0, 'b1205Xs43104s38114', 0, 'guidesgroup_bg', 0, 0, 0, 0, 0, 'officialhabboguides', '2023-05-03 00:00:00');
INSERT INTO groups_details (name, description, owner_id, room_id, badge, recommended, background, views, topics, group_type, forum_type, forum_premission, alias, created_at) VALUES ('SnowStorm', 'Learn all about SnowStorm here!', 1, 0, 'b1216Xs04116s05118s05110s04112', 0, 'snowstorm_bg', 0, 0, 0, 0, 0, 'snow_storm', '2023-05-03 00:00:00');
INSERT INTO groups_details (name, description, owner_id, room_id, badge, recommended, background, views, topics, group_type, forum_type, forum_premission, alias, created_at) VALUES ('BattleBall: Rebound!', 'Learn all about BattleBall here!', 1, 0, 'b1013Xs04038s04064s04100', 0, 'BB_Group2', 0, 0, 0, 0, 0, 'battleball_rebound', '2023-05-03 00:00:00');
INSERT INTO groups_details (name, description, owner_id, room_id, badge, recommended, background, views, topics, group_type, forum_type, forum_premission, alias, created_at) VALUES ('Lido Diving', 'Official Lido Diving group', 1, 0, 'b0816Xs58111s58063s58065', 0, 'bg_lido_flat', 0, 0, 0, 0, 0, 'lido', '2023-05-03 00:00:00');
INSERT INTO groups_details (name, description, owner_id, room_id, badge, recommended, background, views, topics, group_type, forum_type, forum_premission, alias, created_at) VALUES ('Wobble Squabble', 'Learn about Wobble Squabble here!', 1, 0, 'b1201Xs58164s47023s46025', 0, 'WS_Group2', 0, 0, 0, 0, 0, 'wobble_squabble', '2023-05-03 00:00:00');

INSERT INTO cms_recommended (recommended_id, type, is_staff_pick) VALUES (1, 'GROUP', 1);
INSERT INTO cms_recommended (recommended_id, type, is_staff_pick) VALUES (2, 'GROUP', 1);
INSERT INTO cms_recommended (recommended_id, type, is_staff_pick) VALUES (3, 'GROUP', 1);
INSERT INTO cms_recommended (recommended_id, type, is_staff_pick) VALUES (4, 'GROUP', 1);
INSERT INTO cms_recommended (recommended_id, type, is_staff_pick) VALUES (5, 'GROUP', 1);
INSERT INTO cms_recommended (recommended_id, type, is_staff_pick) VALUES (6, 'GROUP', 1);

INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 570, 1078, 42, 11000, 2, 2, '', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 109, 795, 10, 13, 9, 2, '[color=white][b]Owl[/b] The old and wise one - loyal owl  with a heart of gold. Level 10[/color]', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 189, 1069, 12, 13, 2, 2, 'Well of course I can. Because I am a Habbo Guide!', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 109, 197, 2, 13, 9, 2, '[color=white][b]Bunny[/b] The fast one - catch one if  you can. Level 1[/color]', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 109, 331, 1, 13, 9, 2, '[color=white][b]Otter[/b] The one who does not let  you sink. Level 3[/color]', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 110, 728, 9, 13, 9, 2, '[color=white][b]Eagle[/b] The sharp eyed one - flying to  your aid. Level 9[/color]', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 109, 528, 6, 13, 9, 2, '[color=white][b]Lynx[/b] The hunter one - stalks down  answers. Level 6[/color]', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 108, 396, 3, 13, 9, 2, '[color=white][b]Badger[/b] The digger one - has information  you cannot find. Level 4[/color]', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 383, 488, 32, 13, 9, 2, '[color=white][b]Who are Habbo guides?[/b]  Habbo Guides are experienced players  who like to share their knowledge of  Habbo and welcome new players.  Habbo Guides meet and greet new  Habbos, guide them around and generally making them feel at home.  [b]I\'m new. How do I find a Guide?[/b]  The first time you enter your room in the hotel you will be asked if you would like to meet a Habbo Guide. You can also  identify Guides by their animal badge.   [b]What\'s in it for me?[/b]  A warm fuzzy feeling at the end of the  day, and hopefully the start of many new  friendships :)  [b]Can I join?[/b]  Yes, just join this Group. Anyone who\'s interested in being nice to newcomers is welcome to join - the more the merrier![/color]', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 107, 864, 33, 13, 9, 2, '[color=white][b]Wolf[/b] The eXperienced one with  the knowledge to show the way.  Level X[/color]', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 109, 667, 8, 13, 9, 2, '[color=white][b]Bear[/b] The friendly one  - kind and soft. Level 8[/color]', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 639, 489, 31, 13, 9, 2, '[color=white][b]How do we find the new people?[/b]  When new people join Habbo we\'ll ask  them if they\'d like to meet a Guide  from Habbo. If they say yes, we\'ll send alerts to members of this group  who are in the Hotel at the same time.  Accept the invitation and you\'ll be  whisked off to meet the new person.  You can guide them around Habbo and  show them what it\'s about.  [b]Can I get as many invites as I want?[/b]  Sure, with the Guide tool, You can  decide when You want to receive the  invites. After helping someone, you can  pick up the next invite. The Guide tool is  shown on your screen (in the hotel), in the top left corner.  [b]What do I get for guiding?[/b]  Habbo Guides receive badges to  reward their good work. There are 10  levels to achieve. If you successfully  guide a Habbo, who stays in Habbo as a  player, is your friend and has spent  enough time online, you will be rewarded.  The more Habbos you help, the  cooler the badge! These badges are not  available anywhere else.[/color]', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 109, 461, 5, 13, 9, 2, '[color=white][b]Fox[/b] The clever one - is swift of  thought and foot. Level 5[/color]', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 108, 264, 4, 13, 9, 2, '[color=white][b]Bambi[/b] The cutest one - makes you  wanna hug. Level 2[/color]', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 110, 596, 7, 13, 9, 2, '[color=white][b]Buffalo[/b] The strong one - the one you  can depend on. Level 7[/color]', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 25, 1164, 11, 13, 2, 2, 'Hey, I\'m confused. Can you help me?', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 515, 412, 23, 2198, 0, 2, '', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 180, 122, 17, 2206, 0, 2, '', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 630, 411, 25, 2206, 0, 2, '', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 137, 122, 16, 2201, 0, 2, '', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 560, 412, 24, 2214, 0, 2, '', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 786, 411, 29, 2203, 0, 2, '', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 830, 411, 30, 2220, 0, 2, '', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 674, 411, 26, 2222, 0, 2, '', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 471, 412, 22, 2198, 0, 2, '', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 426, 412, 21, 2193, 0, 2, '', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 263, 121, 19, 2220, 0, 2, '', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 720, 411, 27, 2208, 0, 2, '', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 94, 122, 15, 2193, 0, 2, '', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 222, 122, 18, 2203, 0, 2, '', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 50, 121, 14, 2198, 0, 2, '', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 741, 411, 28, 2201, 0, 2, '', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 381, 413, 20, 2207, 0, 2, '', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 26, 11, 105, 11100, 5, 1, '', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 472, 10, 101, 11000, 5, 1, '', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 39, 325, 16, 13, 2, 1, '[b]How do I get around?[/b]  Use the Hotel Navigator to get from room to room. The button is at the bottom of your screen and looks like an orange hotel tower. You’ll be able to visit public rooms, guest rooms. You can also start building your own room by clicking on “Create Own Room” under My Rooms.', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 291, 556, 113, 13, 2, 1, '[b]What if I see someone breaking the rules?[/b]  If you need help from a moderator, you can:  -Use the Call For Help Emergency System. It’s the blue question mark on the bottom right side of your screen.   -May join our Discord ([i]The widget can be found on the /me page[/i]) and tell us what happened.  -May visit our Help Desk: [b]Room Name:[/b] ClassicHabbo Help Desk [b]Room Owner:[/b] Toya', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 487, 357, 111, 13, 2, 1, '[b]Habbo Lingo – just a few words you might need to know:[/b]  [b]Furni[/b] – Furniture [b]Bobba[/b] – When a word is filtered, it comes up as “Bobba” [b]Hand[/b] – Where all your furni ends up when you buy it. [b]Console[/b] – The Habbo Messenger [b]Nav[/b] – The Hotel Navigator [b]Norm[/b] – A non-HC member. [b]HC[/b] – Habbo Club', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 107, 835, 94, 13, 2, 1, '[b]Room Games[/b]  [b]DYP, Defend Your Pod[/b] - A popular room game in Habbo, where each Habbo must defend their own pod while trying to sit in another Habbo’s pod for a brief time to get them out.  [b]FF, Falling Furni[/b] - A game where the owner drops furniture, and the Habbos playing have to race to it. ', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 107, 989, 95, 13, 2, 1, '[b]Dhtw, Don’t Hit The Wall[/b] - A dice is rolled and if it is your number, you move up. First one to the wall losses.  [b]CC, Cozzie Change[/b] - A costume change game, where the host announces a theme and you change your clothes to match the theme.', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 563, 570, 148, 13, 2, 1, '[b]Staff Members:[/b]  [b]Alex[/b] - Administrator & Developer [b]Copyright[/b] - Community Manager [b]Chris[/b] - Community Manager [b]Siract[/b] - Community Manager  [b]Representatives:[/b]  Joee Elijah UnityX Ultra', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 628, 741, 23, 11000, 3, 4, '', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 667, 611, 35, 13, 0, 4, '[b]Tip 5:[/b] Bouncing on your tile three times locks the square- make shapes out of locked tiles to lock all the tiles within.', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 85, 383, 94, 13, 0, 4, '[b][color=#ffce00]Power Drill: [/color][/b][color=#fe6301]Bounce on any tile in  the field to clear it. [/color]', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 369, 317, 20, 13, 4, 4, '[b]Free Battleball[/b]  Yes until further notice we\'re letting you play both SnowStorm and Battleball for free - no tickets required.  [b]Please note:[/b] * skill levels don\'t apply for the free games - everyone can play everyone', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 86, 318, 100, 13, 0, 4, '[b][color=#ffce00]Battle Bomb: [/color][/b][color=#fe6301]Clears all tiles  around it- even yours![/color]', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 30, 30, 16, 13, 2, 4, '[b]Want to know how to play?  Read the instructions in our [url=https://habbolegacy.com/groups/1/id/discussions]discussion forum[/url][/b]', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 84, 452, 83, 13, 0, 4, '[b][color=#ffce00]Light Bulb: [/color][/b][color=#fe6301]Turns all the tiles in a  small area your colour.[/color]', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 84, 584, 96, 13, 0, 4, '[b][color=#ffce00]Flashlight: [/color][/b][color=#fe6301]Colours all the tiles in a  straight line in front of you[/color]', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 85, 255, 89, 13, 0, 4, '[b][color=#ffce00]Box of pins: [/color][/b][color=#fe6301]Bouncing on these will burst your ball![/color]', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 697, 414, 43, 13, 0, 4, '[b]Tip 3:[/b] Distract your opponent by calling him or her strange names like &quot;llama feet&quot;.', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 682, 309, 49, 13, 0, 4, '[b]Tip 2:[/b] Bounce on your own squares multiple times to gain extra points, rather than on empty squares.', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 84, 714, 104, 13, 0, 4, '[b][color=#ffce00]Random: [/color][/b][color=#fe6301]Gives you a power-up chosen at random![/color]', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 683, 254, 47, 13, 0, 4, '[b]Tip 1:[/b] Bouncing over your opponents squares earns you more points than bouncing on empty squares.', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 84, 650, 102, 13, 0, 4, '[b][color=#ffce00]Harlequin: [/color][/b][color=#fe6301]Makes all other players colour tiles for your team.[/color]', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 683, 222, 108, 13, 0, 4, '[size=large][b]Tips & Tactics[/b][/size]', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 669, 532, 31, 13, 0, 4, '[b]Tip 4:[/b] The best power-up is the  Harlequin, while the worse is the box of pins which can harm you most of all!', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 85, 519, 98, 13, 0, 4, '[b][color=#ffce00]Spring: [/color][/b][color=#fe6301]Locks tiles to your colour with a single bounce.[/color]', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 256, 391, 2, 1129, 0, 4, '', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 627, 370, 39, 1129, 0, 4, '', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 799, 211, 1, 212, 0, 4, '', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 476, 492, 34, 11000, 2, 5, '', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 56, 333, 8, 46, 0, 5, '', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 210, 1257, 22, 141, 0, 5, '', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 153, 337, 10, 49, 0, 5, '', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 462, 344, 12, 1308, 0, 5, '', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 59, 414, 19, 56, 0, 5, '', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 215, 321, 11, 52, 0, 5, '', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 222, 410, 14, 47, 0, 5, '', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 171, 439, 16, 39, 0, 5, '', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 273, 416, 13, 45, 0, 5, '', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 141, 238, 7, 54, 0, 5, '', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 271, 470, 15, 1226, 0, 5, '', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 189, 256, 4, 57, 0, 5, '', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 672, 228, 3, 1914, 0, 5, '', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 146, 410, 17, 45, 0, 5, '', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 238, 243, 5, 50, 0, 5, '', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 94, 321, 9, 57, 0, 5, '', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 222, 1267, 6, 1309, 0, 5, '', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 101, 436, 18, 54, 0, 5, '', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 425, 1223, 25, 170, 0, 5, '', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 618, 44, 58, 11000, 4, 6, '', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 63, 613, 55, 13, 0, 6, 'Space', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 85, 713, 23, 13, 0, 6, '[b]Tips &amp; Tactics[/b]', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 40, 542, 53, 13, 0, 6, 'Moving', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 54, 958, 33, 13, 0, 6, '[color=#d80000][b]Tip 2:[/b][/color] If you are wobbling all over  the place, you can get your  balance back once during  the game using the \'stabilise\' button  (space bar).', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 90, 742, 31, 13, 9, 6, '[color=#d80000][b]Tip 1:[/b][/color] When the game starts, you will see a pop up window. On the right is a balance meter.   When the hand points straight up, you\'re perfectly balanced. When it  points to the right, you need to  balance to the left, and vice versa.   If the hand drops too far either side you have lost your balance and will fall into the water and lose.', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 56, 1034, 29, 13, 0, 6, '[color=#d80000][b]Tip 3:[/b][/color] Moving away from your  opponent during a game  will allow you time to balance.', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 334, 955, 14, 13, 4, 6, '[color=#d80000][b]The Queue System[/b][/color]  When you have a ticket, get into the pool, swim over and climb on the inflatables to queue for your turn.   The game starts when two players are ready.', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 178, 468, 35, 13, 0, 6, 'Balance', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 43, 488, 51, 13, 0, 6, 'Push', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 336, 745, 25, 13, 4, 6, '[color=#d80000][b]Buying Tickets[/b][/color]  To play Wobble Squabble, you need tickets. You can get tickets by clicking on the inflatables, or by clicking on the ticket machine beside the pool.  Tickets cost [b][color=#fe6301]6 Credits for 20[/color][/b] or [b][color=#fe6301]1 Credit for 2[/color][/b].   In Wobble Squabble the winner stays on, so if you win a game stay on the inflatables and the next one is free!', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 28, 438, 47, 13, 0, 6, 'Balance', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 760, 248, 3, 1129, 0, 6, '', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 330, 207, 1, 150, 0, 6, '', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 329, 145, 2, 150, 0, 6, '', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 162, 387, 2, 13, 2, 3, '[b]Eeek, collision course![/b]', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 644, 11, 19, 11000, 5, 3, '', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 69, 194, 6, 13, 2, 3, '[b]Hey dude! Don\'t you know the rules? Check out the How to Play thread in the [url=https://habbolegacy.com/groups/snowstorm/discussions]discussion forum[/url][/b]', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 516, 1083, 1, 13, 2, 3, '[b]Not again...[/b]', 1, '');
INSERT INTO cms_stickers (user_id, x, y, z, sticker_id, skin_id, group_id, text, is_placed, extra_data) VALUES (1, 556, 317, 4, 183, 0, 3, '', 1, '');

SELECT TABLE_NAME, TABLE_ROWS FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'havana' ORDER BY TABLE_NAME;